# https://rust-lang.github.io/rustfmt/?version=v1.4.38
indent_style = "Block"
reorder_imports = true
blank_lines_upper_bound = 1
wrap_comments = true
enum_discrim_align_threshold = 30
format_strings = true
max_width = 80
group_imports = "StdExternalCrate"
